### ISSUE TITLE
auraliser.py is missing

### ISSUE THREAD

**Issue by dizcza** [FRidh/phd_thesis#3]
Dear Frederik,

thank you for sharing your PhD project. I was looking for usages of the `acoustics.reflection` module (in fact, I've opened an [issue](https://github.com/python-acoustics/python-acoustics/issues/249) in python-acoustics) and came upon this repository. Sadly, you're the only user of the `reflection` module of the python-acoustics package as far as I can search through all Github pages.

`nix-build -A thesis` does not seem to work any longer, but I see that you know it already. I'd like to see the source code of `auraliser.py` to go through https://github.com/FRidh/phd_thesis/blob/master/nix/packages/common_simulation.py#L87-L91 but I cannot find the implementation of `rcv.auralise()` as well as many other components involved in this script.

Would you mind sharing the implementation?

I'd also like to have a look at the thesis itself but I don't understand where the main TeX compiled file is.

Thank you.

Best,
Danylo

**Comment by FRidh** [comment]
Hi

Yes, I wrote the `reflection` module for this purpose. 

All packages used can be found in https://github.com/FRidh/phd_thesis/blob/v1.0.1/nix/packages/default.nix.

You are probably looking for the `auraliser` package https://github.com/FRidh/auraliser.

**Comment by FRidh** [comment]
> I'd also like to have a look at the thesis itself but I don't understand where the main TeX compiled file is.

In https://github.com/FRidh/phd_thesis/blob/master/nix/thesis-source/default.nix all assets are put together in a folder.
In https://github.com/FRidh/phd_thesis/blob/master/nix/thesis/default.nix the files are compiled into a pdf.
The pdf can be found at http://publications.lib.chalmers.se/records/fulltext/251306/251306.pdf.

**Comment by dizcza** [comment]
Wow, you've made lots of effort putting those things in `auraliser`. It's sad to see that such projects are discontinued.

Thanks for the pdf link, I've not managed to compile the scripts with the `nix-build` command.

----

Looking closely at auraliser example notebooks and the code structure, I understand that you've created this package mainly for yourself. I think, if you were affiliated with a university where such acoustics studies are performed (therefore, where grant could be issued), you could push the package to the users by working on the documentation, refactoring, etc.

**Comment by FRidh** [comment]
> Wow, you've made lots of effort putting those things in auraliser. It's sad to see that such projects are discontinued.

Thanks. It's indeed a pity these kind of projects end when the funding is over. The current implementation is quite experimental though; my approach to performing these type of simulations changed as well (from a fixed length auralisation to a variable length soft real-time one) so the current tree is a mix of methods that could very well be improved.
